"""Added Category Model

Revision ID: 07fd4e302761
Revises: 2e7e0ea5cc19
Create Date: 2024-03-09 02:21:06.762661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fd4e302761'
down_revision = '2e7e0ea5cc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=100), nullable=True),
    sa.Column('cat_description', sa.Text(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cat_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
