"""changed the fav_color in the Users table to address

Revision ID: 265647af6ad5
Revises: bb131f66a357
Create Date: 2024-04-08 03:35:06.812608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265647af6ad5'
down_revision = 'bb131f66a357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.drop_column('fav_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_color', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
